# -*- coding: utf-8 -*-
"""hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRwurOx0WzfnC2AxkIATLO9xl1QE-gZR
"""

import os
import azure.cognitiveservices.speech as speechsdk
from langchain.text_splitter import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.chains.question_answering import load_qa_chain
from langchain_community.callbacks import get_openai_callback
from langchain_community.chat_models import ChatOpenAI
from langchain_openai import ChatOpenAI
from PyPDF2 import PdfReader
from docx import Document
import os
import requests
import json
import openai
import tiktoken

def recognize_from_microphone():
    azure_api_key = "YOUR_API_KEY_HERE"
    azure_region = "YOUR_AZURE_SPEECH_REGION_HERE"

    speech_config = speechsdk.SpeechConfig(subscription=azure_api_key, region=azure_region)
    speech_config.speech_recognition_language="zh-TW"

    audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    print("Speak into your microphone.")
    speech_recognition_result = speech_recognizer.recognize_once_async().get()

    if speech_recognition_result.reason == speechsdk.ResultReason.RecognizedSpeech:
        print("Recognized: {}".format(speech_recognition_result.text))
    elif speech_recognition_result.reason == speechsdk.ResultReason.NoMatch:
        print("No speech could be recognized: {}".format(speech_recognition_result.no_match_details))
    elif speech_recognition_result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = speech_recognition_result.cancellation_details
        print("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            print("Error details: {}".format(cancellation_details.error_details))
            print("Did you set the speech resource key and region values?")

    return speech_recognition_result.text

def get_openai_response(speech_content):
    chat_history = []
    os.environ['OPENAI_API_KEY'] = "YOUR_OPENAI_API_KEY_HERE"

    def get_text_from_pdf(pdf_path):
       text = ""
       with open(pdf_path, 'rb') as file:
            pdf_reader = PdfReader(file)
            for page in pdf_reader.pages:
                text += page.extract_text()
       return text

    def get_text_from_docx(docx_path):
        doc = Document(docx_path)
        text = ""
        for paragraph in doc.paragraphs:
            text += paragraph.text + "\n"
        return text

    user_input = speech_content

    if user_input:
        files_folder = '你data的路徑'
        text = ""

        for filename in os.listdir(files_folder):
            file_path = os.path.join(files_folder, filename)
            if filename.endswith('.pdf'):
                text += get_text_from_pdf(file_path)
            elif filename.endswith('.docx'):
                text += get_text_from_docx(file_path)

        text_splitter = CharacterTextSplitter(
            separator="\n",
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len
        )
        chunks = text_splitter.split_text(text)

        embeddings = OpenAIEmbeddings()
        knowledge_base = FAISS.from_texts(chunks, embeddings)

        docs = knowledge_base.similarity_search(user_input)

        llm = ChatOpenAI(
            model_name="gpt-4-1106-preview",
            temperature=0.4
        )

        chain = load_qa_chain(llm, chain_type="stuff")

        with get_openai_callback() as cb:
            response = chain.run(input_documents=docs, question=user_input)

        response = {'response': response}
        print("Response from Assistant:", response['response'])
        chat_history.append({'user': user_input, 'assistant': response['response']})

        return response['response']

def text_to_speech(response_content):
    #此範例需要名為「SPEECH_KEY」和「SPEECH_REGION」的環境變量
    azure_api_key = "YOUR_AZURE_SPEECH_API_KEY_HERE"
    azure_region = "YOUR_AZURE_SPEECH_REGION_HERE"

    speech_config = speechsdk.SpeechConfig(subscription=azure_api_key, region=azure_region)
    audio_config = speechsdk.audio.AudioOutputConfig(use_default_speaker=True)

    #說話的聲音的語言。
    speech_config.speech_synthesis_voice_name='zh-CN-XiaoxiaoNeural'

    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)

    #從控制台取得文字並合成到預設揚聲器。
    print("Enter some text that you want to speak >")
    text = response_content

    speech_synthesis_result = speech_synthesizer.speak_text_async(text).get()

    if speech_synthesis_result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
        print("Speech synthesized for text [{}]".format(text))
        #將內容存成 wav 檔
        audio_data=speech_synthesis_result.audio_data
        with open("你想要的存檔路徑", "wb") as audio_file:
            audio_file.write(audio_data)
    elif speech_synthesis_result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = speech_synthesis_result.cancellation_details
        print("Speech synthesis canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            if cancellation_details.error_details:
                print("Error details: {}".format(cancellation_details.error_details))
                print("Did you set the speech resource key and region values?")

speech_result = recognize_from_microphone()
print(speech_result)

response_content = get_openai_response(speech_result)
print(response_content)

text_to_speech(response_content)