# -*- coding: utf-8 -*-
"""Embedding_AI_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zjUO5eY57KiIHuMwoWaPoHzO_5arI1Z
"""

!pip install flask langchain PyPDF2 python-docx requests
!pip install --upgrade openai
!pip install tiktoken
!pip install faiss-cpu

from google.colab import drive
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.chains.question_answering import load_qa_chain
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI
from PyPDF2 import PdfReader
from docx import Document
import os
import requests
import json
import openai
import tiktoken

drive.mount('/content/drive')
chat_history = []

os.environ['OPENAI_API_KEY'] = "YOUR_OPENAI_API_KEY_HERE"

def get_text_from_pdf(pdf_path):
    text = ""
    with open(pdf_path, 'rb') as file:
        pdf_reader = PdfReader(file)
        for page in pdf_reader.pages:
            text += page.extract_text()
    return text

def get_text_from_docx(docx_path):
    doc = Document(docx_path)
    text = ""
    for paragraph in doc.paragraphs:
        text += paragraph.text + "\n"
    return text

user_input = "你是一名美容產品的推銷員，你現在的顧客是一位25歲無皺紋無黑斑的女士，為了解決問題，你要向她推薦一件克蘭詩產品"

if user_input:
    files_folder = '/content/drive/MyDrive/Colab Notebooks/生成式'
    text = ""

    for filename in os.listdir(files_folder):
        file_path = os.path.join(files_folder, filename)
        if filename.endswith('.pdf'):
            text += get_text_from_pdf(file_path)
        elif filename.endswith('.docx'):
            text += get_text_from_docx(file_path)

    text_splitter = CharacterTextSplitter(
        separator="\n",
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )
    chunks = text_splitter.split_text(text)

    embeddings = OpenAIEmbeddings()
    knowledge_base = FAISS.from_texts(chunks, embeddings)

    docs = knowledge_base.similarity_search(user_input)

    llm = ChatOpenAI(
        model_name="gpt-4-1106-preview",
        temperature=0.4
    )

    chain = load_qa_chain(llm, chain_type="stuff")

    with get_openai_callback() as cb:
        response = chain.run(input_documents=docs, question=user_input)

    response = {'response': response}
    print("Response from Assistant:", response['response'])
    chat_history.append({'user': user_input, 'assistant': response['response']})

    def create_a_talk(word, api_key):
      url = "https://api.d-id.com/talks"

      payload = {
          "script": {
              "type": "text",
              "subtitles": "false",
              "provider": {
                  "type": "microsoft",
                  "voice_id": "zh-CN-XiaoxiaoNeural"
              },
              "ssml": "false",
              "input": word
          },
          "config": {
              "fluent": "false",
              "pad_audio": "0.0"
          },
          "source_url": "https://create-images-results.d-id.com/api_docs/assets/noelle.jpeg"
      }
      headers = {
          "accept": "application/json",
          "content-type": "application/json",
          "authorization": "Basic " +api_key
      }
      response = requests.post(url, json=payload, headers=headers)
      response_json = json.loads(response.text)
      talk_id = response_json['id']
      url = "https://api.d-id.com/talks/" +talk_id
      headers = {
          "accept": "application/json",
          "authorization": "Basic " +api_key
      }
      while True:
        response = requests.get(url, headers=headers)
        response_json = json.loads(response.text)
        status = response_json.get('status')
        if status == 'done':
          break

      result_url = response_json['result_url']

      return result_url

    d_id_api = "Y2h1bmcudGluYTA2MjJAZ21haWwuY29t:mUq8oDXQMOv1POxY6qexr"
    result_url = create_a_talk(response['response'], d_id_api)
    print("D-ID Result URL:", result_url)